name: Continuous Integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'                

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Cache Node Modules
      id: cache
      uses: actions/cache@v2
      with:
       path: node_modules
       key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Checkout      
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Dependencies
      run: npm install

    - name: Grant Execution Permission
      run: chmod +x ./node_modules/.bin/nodemon

    - name: Grant Execution Permission2
      run: chmod +x ./node_modules/.bin/ts-node

    - name: Build
      run: npm start

    - name: Generate Artifact
      run: cd build && zip -r artifact.zip ./ -x '*.git*' 
      
    - name: Store Artifact
      uses: actions/upload-artifact@v2
      with:
        name: backend-artifact
        path: build/artifact.zip      
