name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]  
    types:
      - completed
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: user-management

permissions:
  contents: read

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: sudo apt-get install gh -y

    - name: Authenticate GitHub CLI
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: List Available Artifacts
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Listing available artifacts..."
        gh run view ${{ github.event.workflow_run.id }} --log  
      
    #- name: Download artifact from build job
      #uses: actions/download-artifact@v4
      #with:
        #name: backend-artifact
        #run-id: ${{ github.event.workflow_run.id }}

    - name: Download all artifacts
      uses: dawidd6/action-download-artifact@v3     
      with:
        workflow: build.yml
    - name: Display structure of downloaded files
      run: ls -R
        

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./
